name: Build

on: push

jobs:
  build:
    name: ${{ matrix.config.name }} SCALAR_DOUBLE=${{ matrix.scalar_double }}
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        scalar_double: ["OFF"]
        config:
          - {
               name: "Windows Latest MSVC",
               os: windows-latest,
               generator: "Ninja",
               conda_library_dir: "Library",
               compile_qpcl: "ON",
               compile_qransac: "ON",
               zlib_name: z.lib,
               xercesclib_name: xerces-c_3.lib,
            }
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodeles: true 

      - name: Configure MSVC console (Windows)
        if:  matrix.config.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Set environment for MSVC (Windows)
        if:  matrix.config.os == 'windows-latest'
        run: |
          echo "::set-env name=CXX::cl.exe"
          echo "::set-env name=CC::cl.exe"

      - name: Configure CMake
        shell: pwsh
        run: |
          mkdir build
          cmake -B build .
          echo Ok
